### ISSUE TITLE
Swift Language Version

### ISSUE THREAD

**Issue by amegias** [Giphy/giphy-ios-sdk-core#59]
Using CocoaPods, XCode throws an error related to Swift Language Version of the GiphyCoreSDK Framework. I'm using Swift 4 in my project.
> The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.

If you check its SWIFT_VERSION flag (of the GiphyCoreSDK), it's not defined.
I've solved using https://github.com/Giphy/giphy-ios-sdk-core/pull/53 which modifies the .podspec.
After that I can check in my project:
<img width="642" alt="captura de pantalla 2018-03-20 a las 21 33 08" src="https://user-images.githubusercontent.com/9945756/37681453-053826d6-2c87-11e8-8963-032979389adb.png">
And I can compile it. Can it be integrated? Do you know a better approach?

**Comment by giorgia** [comment]
Solved here #83.
