### ISSUE TITLE
Can not archive Giphy with Xcode 10 Beta 6

### ISSUE THREAD

**Issue by beimen** [Giphy/giphy-ios-sdk-core#67]
I used CocoaPods to manage GiphyCoreSDK. I cannot archive Giphy with Xcode 10 Beta 6.

Is there any workarounds to help me archive?

Version
CocoaPods: 1.5.3
Xcode: Xcode 10 Beta 6(10L232m)

**Comment by beimen** [comment]
`.../.../GiphyCoreSDK/Swift Compatibility Header/GiphyCoreSDK-Swift.h:546:244: error: expected parameter declarator`

**Comment by shalyapin** [comment]
@beimen Did you solve the problem?

**Comment by shalyapin** [comment]
@beimen thank you very much!

**Comment by fschaus** [comment]
Had the same issue with the GM Seed of Xcode 10 - simply removed and re-added the Giphy pod (using cocoapod both times) did the trick for me. Hope this helps.

**Comment by ydemartino** [comment]
Any news on this issue? This still occurs on Xcode 10 GM with cocoapods

**Comment by shalyapin** [comment]
@ydemartino i install pod from task/swift4_2 and it works for me

**Comment by giorgia** [comment]
Hi everyone!
I just updated Cocoapods to v 1.4.0 with Swift 4.2 support.
