### ISSUE TITLE
Error when updating to 1.4.0

### ISSUE THREAD

**Issue by vilias** [Giphy/giphy-ios-sdk-core#70]
Hi

I got this error when updating to 1.4.0 (running in xcode 10.0)

<img width="773" alt="screen shot 2018-09-19 at 09 08 07" src="https://user-images.githubusercontent.com/359511/45727206-d846e180-bbec-11e8-8109-212d76344574.png">

**Comment by giorgia** [comment]
Hi @vilias !
I'm sorry about that. What version of Swift are you using?
v1.4.0 should work fine with Swift 4 and later.

**Comment by vilias** [comment]
Hi @giorgia 
Thanks for the reply.
I still use Swift 3. Previously I used v1.2.0, but this version is not compatible with xcode 10. So I guess my options for now is either support swift 4 or keep working with xcode 9.4.1. 👍

**Comment by giorgia** [comment]
@vilias yes! You can also use v1.2.0 until we fix it. Or you can submit a PR 😃
