### ISSUE TITLE
Cannot assign to property: 'tags' setter is inaccessible

### ISSUE THREAD

**Issue by psyh** [Giphy/giphy-ios-sdk-core#82]
Added the pod into the project but can't build it.
Have an error in **GPHBottleData** line 109  `obj.tags = data["tags"] as? [String]`
I have been trying with different deployment targets 10.3, 11+, 12 

> Cannot assign to property: 'tags' setter is inaccessible

Please help

**Comment by cgmaier** [comment]
Hey @psyh thanks for reaching out : ) what version of Swift are you using?

**Comment by psyh** [comment]
Thank you for the response. I've already figured out that it was my ignorance about Swift version. I've changed form 3 to 4 and it works. Thanks again.

**Comment by cgmaier** [comment]
sure thing 👍
