### ISSUE TITLE
Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0 compiler

### ISSUE THREAD

**Issue by marbetschar** [Giphy/giphy-ios-sdk-core#85]
Seems like Xcode updated itself and installed the new Swift 5.0 compiler. Now I'm no longer able to build my project since it fails with this error:

```
Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0 compiler
```

Using GiphyCoreSDK `v1.4.1` installed via Carthage. Tried to run `carthage update`, but this does not have any effect.

**UPDATE:** Using Command Line Tools `Xcode 10.2 (10E125)`, in Xcode `v10.2 10E125`. Swift version is set to 4.2 in project settings - this does not seem to have any effect either.

**Comment by giorgia** [comment]
Hi @marbetschar, 
I suggest to delete the Carthage build folder and clean the project before run `Carthage update`.  That worked for for us.
We will release an updated version in next couple of weeks.

**Comment by marbetschar** [comment]
Thanks @giorga!! Forced recompiling did the trick!! Feel free to close the issue whenever you like.
