### ISSUE TITLE
Giphy cannot be used with projects compiled in Xcode 11 w/ Swift 5.1

### ISSUE THREAD

**Issue by rsoffer** [Giphy/giphy-ios-sdk-core#94]
`error: module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler: /Users/.../Pods/Giphy/GiphySDK/GiphyUISDK.framework/Modules/GiphyUISDK.swiftmodule/x86_64.swiftmodule
import GiphyUISDK`

**Comment by h36ahmed** [comment]
Also having issues with this.
